apiVersion: v1
kind: PersistentVolume
metadata:
  name: ukf-pv-volume
  namespace: ukf
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOncePod
  hostPath:
    path: "/mnt/data"
