apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ukf
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: shared-html
          emptyDir: {}
      terminationGracePeriodSeconds: 60
      containers:
        - name: vk-php
          image: ppsdocker/vk-php:latest
          imagePullPolicy: Always
          command:
            - /usr/local/sbin/php-fpm
            - '--force-stderr'
            - '--nodaemonize'
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          volumeMounts:
            - name: shared-html
              mountPath: /var/www/html
        - name: nginx
          image: library/nginx:1.20.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-html
              mountPath: /var/www/html
